# Application
app:
  debug: true
  hostname: "0.0.0.0"
  port: 8700
  lang: zh-CN     # 默认语言
  charset: UTF-8  # 全局默认字符集
  timeZone: GTM+8  # 时区
  pageSize: 20    # 默认分页大小

cache:
  path: /cache    # 缓存路径
  timeout: 3600   # 失效时间
  sign: md5       # 使用MD5算法
  handler: memory # 内存缓存

logging:
  path: /logs     # 默认路径
  charset: UTF-8  # 内容编码
  handler: TimedRotatingHandler

url:
  caseSensitive: false  # 忽略大小写
  static:    # 静态资源路径名，和对应文件夹同名
    [
      "static",
      "D:\\",
    ]

# module
module:
  path:
    module: index       # 默认模块
    controller: index   # 默认控制器
    action: index       # 默认方法
  dirname:    # 目录名称，相对模块的路径
    controller: "controller"   # 控制器包名
    model: model   # 模型包名
    view: view     # 视图包名
    lang: lang     # 语言包名
    validator: validator  # 验证器包名
  forb: # 禁止访问的模块
    ["common", "test"]

# view
view:
  cache: true
  engine: default # 模板引擎

# session
session:
  type: memory      # 保存方式，支持：file、memory
  name: QSESSION    # session 名
  format: md5       # session ID 生成方式
  expire: 604800    # 有效时间，秒，默认7天
  httponly: true    # 绑定http协议

# Exception
exception:
  handle: default   # 处理方式，default=默认框架处理
  defaultMessage: 页面暂时无法访问

log:
  name: demo
  handle: default
  path: "log"   # 日志目录，工作目录相对路径
  fileName: "%y-%m-%d.log"
  level: DEBUG

# Database
database2:
  url: jdbc:mysql://127.0.0.1:3306/www_lcdp_com?useSSL=false
  driver: com.mysql.jdbc.Driver
  username: root
  password: 123456

database:
  url: jdbc:mysql://192.168.10.53:53306/www_lcdp_com?useSSL=false
  driver: com.mysql.jdbc.Driver
  username: www_lcdp_com
  password: X3yTEyF8PeYJkfnA
