# Application
app:
  debug: true
  domin: "www.demo.com"
  version: 1.0
  lang: zh-CN     # 默认语言
  charset: UTF-8  # 全局默认字符集

url:
  caseSensitive: false  # 默认忽略大小写

# 模块
module:
  dirname:
    controller: controller   # 控制器包名
    model: model   # 模型包名
    view: view     # 视图包名
    lang: lang     # 语言包名
    validator: validator  # 验证器包名
  default:
    module: index       # 默认模块
    controller: index   # 默认控制器
    action: index       # 默认方法
  close: # 禁止访问的模块
    ["common"]

# 视图
view:
  type: default

# session
session:
  id: ''    # session 上该应用的ID
  name: 'QSESSION'  # session 名
  format: md5   # session生成方式
  expire: 7    # 有效时间，天
  httponly: true

# 异常
exception:
  handle: default # 处理方式，default=默认框架处理
  defaultMessage: 页面暂时无法访问

# 日志
log:
  handle: default
  path: ''
  fileName: "%y-%m-%d.log"
  level: debug
  server:
    host: localhost
    username: quick
    password: 123456

# Database
database:
  url: jdbc:mysql://127.0.0.1:3306/?useUnicode=true&characterEncoding=utf-8
  database: quickjava
  username: quickjava
  password: quickjava
