# Application
app:
  debug=true
  name=Demo
  domin=www.demo.com
  version=1.0

# Database
database:
  url=jdbc:mysql://127.0.0.1:3306/?useUnicode=true&characterEncoding=utf-8
  database=quickjava
  username=quickjava
  password=quickjava
