# Application
app:
  hostname: "0.0.0.0"
  port: 8080
  debug: true
  version: 1.0
  versionCode: 101000
  lang: zh-CN     # 默认语言
  charset: UTF-8  # 全局默认字符集

url:
  caseSensitive: false  # 默认忽略大小写

# module
module:
  default:
    module: index       # 默认模块
    controller: index   # 默认控制器
    action: index       # 默认方法
  dirname:    # 目录名称，相对模块的路径
    controller: module   # 控制器包名
    model: model   # 模型包名
    view: view     # 视图包名
    lang: lang     # 语言包名
    validator: validator  # 验证器包名
  forb: # 禁止访问的模块
    ["common"]

# render
view:
  engine: default # 模板引擎

# session
session:
  name: QSESSION  # session 名
  format: md5       # session ID 值生成方式
  expire: 7         # 有效时间，天
  httponly: true

exception:
  handle: default   # 处理方式，default=默认框架处理
  defaultMessage: 页面暂时无法访问

log:
  name: demo
  handle: default
  path: "log"   # 日志保存目录，程序相对路径
  fileName: "%y-%m-%d.log"
  level: DEBUG
  server:
    [{
        host: localhost,
        password: 123456,
      },
    ]

# Database
database:
  url: jdbc:mysql://127.0.0.1:3306/?useUnicode=true&characterEncoding=utf-8
  database: quickjava
  username: quickjava
  password: quickjava
